### ISSUE TITLE
How to input file paths from other nodes

### ISSUE THREAD

**Issue by norsizu** [Chaoses-Ib/ComfyUI_Ib_CustomNodes#1]
Thanks for writing such a handy plugin. I have a question, the image path is supposed to be in text format, but if I try to convert the image to input from another text or string node, I get an error, 
ERROR:root: - Exception when validating inner node: 'NoneType' object has no attribute ' endswith'
ERROR:root:Output will be ignored
<img width="550" alt="20240229" src="https://github.com/Chaoses-Ib/ComfyUI_Ib_CustomNodes/assets/2382750/d6e1ef90-e94f-4d04-9a59-e4cc6d220299">
What should I do to solve this problem, thanks .

**Comment by Chaoses-Ib** [comment]
Fixed. Please run `git pull` or use ComfyUI-Manager to update.

**Comment by norsizu** [comment]
Thank you so much.
