### ISSUE TITLE
Usage Example

### ISSUE THREAD

**Issue by gibiee** [Chaoses-Ib/ComfyUI_Ib_CustomNodes#4]
This is exactly the function I was looking for!
However, it's unfortunate that the lack of concrete usage examples makes it difficult to grasp the function at a glance.
To make it easier for more people to use, I'd like to sharing some relevant information.

**Installation** : Install via the Custom Node Manager in ComfyUI-Manager.
**Screenshot**
![usage](https://github.com/user-attachments/assets/e43c85dc-1057-4f49-b1fb-1938989f6f37)

**Comment by gibiee** [comment]
@Chaoses-Ib Would it be okay if I send a PR for the `README.md`?

**Comment by Chaoses-Ib** [comment]
PR is welcome.

**Comment by gibiee** [comment]
I'm so glad it merged!
